theme = "kanagawa-dragon-improved"

[editor]
bufferline = "always"
color-modes = true
cursorcolumn = true
cursorline = true
jump-label-alphabet = "fjdkslghabnvmctyrueiwoxqpz"
line-number = "relative"
rulers = [88]
scrolloff = 10
shell = ["zsh", "-c"]
text-width = 88
true-color = true

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
S-d = "kill_to_line_end"
esc = ["collapse_selection", "keep_primary_selection"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.normal.space.b]
b = "buffer_picker"
d = ":buffer-close"
c = ":write-buffer-close"
w = ":write-all"
o = ":buffer-close-others"
n = "goto_next_buffer"
p = "goto_previous_buffer"
v = ":vsplit-new"
h = ":hsplit-new"


[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
